apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: "http://vault.vault.svc.cluster.local:8200" # Optional. Default: "https://127.0.0.1:8200"
  # - name: caCert # Optional. This or caPath or caPem
  #   value: "[ca_cert]"
  # - name: caPath # Optional. This or CaCert or caPem
  #   value: "[path_to_ca_cert_file]"
  # - name: caPem # Optional. This or CaCert or CaPath
  #   value : "[encoded_ca_cert_pem]"
  - name: skipVerify # Optional. Default: false
    value : "false"
  # - name: tlsServerName # Optional.
  #   value : "[tls_config_server_name]"
  - name: vaultToken # Required if vaultTokenMountPath not provided. Token value.
    value : <YOUR_TOKEN>
  - name: vaultKVPrefix # Optional. Default: "dapr"
    value : "webapp"
  - name: vaultKVUsePrefix # Optional. default: "true"
    value: "true"
  - name: enginePath # Optional. default: "secret"
    value: "secret"
  - name: vaultValueType # Optional. default: "map"
    value: "map"
